version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "wolffaxn"

  - package-ecosystem: pip
    directory: "/"
    groups:
      python-packages:
        patterns:
          - "*"
    schedule:
      interval: daily
    assignees:
      - "wolffaxn"
