services:
  qdrant:
    image: docker.io/qdrant/qdrant:v1.11.0
    container_name: qdrant
    environment:
      - TZ=Europe/Berlin
    ports:
      - 6333:6333
      - 6334:6334
    networks:
      - ollama-net
    volumes:
      - ./data:/qdrant/storage:z
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ollama-net"
      - "traefik.http.routers.qdrant.rule=Host(`qdrant.localhost`)"
      - "traefik.http.routers.qdrant.entrypoints=web"
      - "traefik.http.routers.qdrant.service=qdrant"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"
    restart: unless-stopped

networks:
  ollama-net:
    external: true
