services:
  qdrant:
    image: docker.io/qdrant/qdrant:v1.11.3
    container_name: qdrant
    environment:
      - TZ=Europe/Berlin
    ports:
      - 6333:6333
      - 6334:6334
    networks:
      - ollama-net
    volumes:
      - ./data:/qdrant/storage:z
    labels:
      traefik.enable: true
      traefik.docker.network: ollama-net
      traefik.http.routers.qdrant.rule: Host(`qdrant.localhost`)
      traefik.http.routers.qdrant.entrypoints: websecure
      traefik.http.routers.qdrant.tls: true
      traefik.http.routers.qdrant.service: qdrant
      traefik.http.services.qdrant.loadbalancer.server.port: 6333
    depends_on:
      traefik:
        condition: service_healthy
    restart: unless-stopped

networks:
  ollama-net:
    external: true
