## STATIC CONFIG (restart traefik to update)

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# logging
log:
  filePath: /var/log/traefik/traefik.log
  format: json
  level: DEBUG

accesslog:
  filePath: /var/log/traefik/access.log
  format: json
  fields:
    defaultMode: keep

# enable traefik ui dashboard
api:
  dashboard: true
  disableDashboardAd: true
  debug: false
  insecure: false

# traefik entrypoints configuration
entryPoints:
  # HTTP(S)
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          scheme: https
          to: websecure
          permanent: true
  websecure:
    address: :443
  # TCP
  redis:
    address: :6379

# enable ping so the `traefik healthcheck` works
ping: {}

providers:
  docker:
    exposedByDefault: false
    endpoint: 'unix:///var/run/docker.sock'
    watch: true
  file:
    directory: /etc/traefik/conf/
    watch: true
