services:
  pipelines:
    container_name: pipelines
    image: docker.io/wolffaxn/pipelines:main
    environment:
      - TZ=Europe/Berlin
    # ports:
    #   - 9099:9099
    networks:
      - backend
    volumes:
      - ./data:/app/pipelines
    labels:
      traefik.enable: true
      traefik.http.routers.pipelines.entrypoints: websecure
      traefik.http.routers.pipelines.tls: true
      traefik.http.routers.pipelines.rule: Host(`pipelines.localhost`)
      traefik.http.services.pipelines.loadbalancer.server.port: 9099
    depends_on:
      traefik:
        condition: service_healthy
    restart: unless-stopped

networks:
  backend:
    external: true
