services:
  pipelines:
    image: docker.io/wolffaxn/pipelines:main
    container_name: pipelines
    environment:
      - TZ=Europe/Berlin
    ports:
      - 9099:9099
    networks:
      - ollama-net
    volumes:
      - ./data:/app/pipelines
    labels:
      traefik.enable: true
      traefik.docker.network: ollama-net
      traefik.http.routers.pipelines.rule: Host(`pipelines.localhost`)
      traefik.http.routers.pipelines.entrypoints: websecure
      traefik.http.routers.pipelines.tls: true
      traefik.http.routers.pipelines.service: pipelines
      traefik.http.services.pipelines.loadbalancer.server.port: 9099
    depends_on:
      traefik:
        condition: service_healthy
    restart: unless-stopped

networks:
  ollama-net:
    external: true
