## STATIC CONFIG (restart traefik to update)

# shows you a log msg if a newer image tag can be used
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# log default is ERROR, but WARN is more helpful
log:
  level: DEBUG
#  level: INFO
  format: common
  filePath: /var/log/traefik/traefik.log

accesslog:
  format: common
  filePath: /var/log/traefik/access.log

# enable dashboard on 8080 with NO AUTH
api:
  dashboard: true
  disableDashboardAd: true
  insecure: true

# listen on port 80/443
entryPoints:
  redis:
    address: :6379
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          scheme: https
          to: websecure
          permanent: true
  websecure:
    address: :443

# enable ping so the `traefik healthcheck` works
ping: {}

providers:
  docker:
    # -- (Optional) Enable this, if you want to expose all containers automatically
    exposedByDefault: false
    watch: true
  file:
    directory: /etc/traefik
    watch: true

## DYNAMIC CONFIG

tls:
  certificates:
    - certFile: /certs/localhost.crt
      keyFile: /certs/localhost.key
  # options:
    # default:
      # sniStrict: true
