services:
  ollama:
    container_name: ollama
    image: docker.io/ollama/ollama:0.3.6
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=-1
      - TZ=Europe/Berlin
    ports:
      - 7869:11434
    networks:
      - ollama-net
    tty: true
    volumes:
      - ./data:/root/.ollama
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ollama-net"
      - "traefik.http.routers.ollama.rule=Host(`ollama.localhost`)"
      - "traefik.http.routers.ollama.entrypoints=web"
      - "traefik.http.routers.ollama.service=ollama"
      - "traefik.http.services.ollama.loadbalancer.server.port=11434"
    restart: unless-stopped

networks:
  ollama-net:
    external: true
